# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac4f8267b00b2518c199a7d508e74a02cf5328966a1609b2ac14ceff267d134a998106a25c90449d2cb019bfcd3da4b5505efb61cd110df85aeed83c536de392

test:
  secret_key_base: d90c3fe537017ffe0ffb9771d4612eaf9b9a549f86838d1c321b8ac40b6f0be4bdea48287d00247ac7f25433d1a1a8319dfbd5e3acdad4c97b5bdde19585deae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
